
num_jobs: 1 # number of parallel jobs
max_iter: 50 # maximum number of iterations
num_points: 1  # How many points explored per iteration
num_initial: 50 # Number of points in initial design
fds_command: C:/Program Files/firemodels/FDS6/bin/fds.exe
variables:
          KS300: [ 0.2, 0.9]
          KS600: [ 0.2,  0.9]
          CS600: [ 1.20,   2.5]
          RHOC : [150,400]
          KC   : [ 0.01, 0.3]
simulation:
    MLR: {fname: 'cone_hrr.csv',dep_col_name: 'MLR_TOTAL',ind_col_name: 'Time',conversion_factor: 100000}
    HRR: {fname: 'cone_hrr.csv',dep_col_name: 'HRR',ind_col_name: 'Time',conversion_factor: 100}
experiment:
    MLR: {fname: '09090043_red.CSV',dep_col_name: 'Specific MLR',ind_col_name: 'Time',header: 1} # header: 1 skips the first line
    HRR: {fname: '09090043_red.CSV',dep_col_name: 'HRR',ind_col_name: 'Time',header: 1}
obejctive:
    type: "RMSE"
    weights: {'MLR': 1.0, 'HRR': 0.0}
plots:
    MLR: {variables: ["MLR"],labels: [""],ylabel: "MLR (g/m$^2$s)", xlabel: "Time (s)", type: "comparison"}
    HRR: {variables: ["HRR"],labels: [""],ylabel: "MLR (g/m$^2$s)", xlabel: "Time (s)", type: "comparison"}
templates: ["birch_cone.fds"]
