#start_config
num_jobs: 1 # number of parallel jobs
max_iter: 0 # maximum number of iterations
num_points: 1  # How many points explored per iteration
num_initial: 1 # Number of points in initial design
fds_command: /home/tstopi/Firemodels/fds/Build/mpi_intel_linux_64/fds_mpi_intel_linux_64
variables:
  YBIRCH0: [0,1]
  A: [1E10,1E14]
  E: [1E4,1E6]
  NUCHAR: [0,1]
#    A   = 2.75E12
#    E    = 1.75E5
#simulation - simulation outputfiles
#entries in format:
#   Var_name: output_file, col name, conversion factor
#Var_name is used to match the simulation output and experimental data
#output_file gives the fiel where this output is located int
#col name gives the column name in output file
#conversion factor  factor for converting from e.g. g to kg (i.e, c in  y=c*x)
#experiment - experimental data in same format
#   Var_name: data_file, col name, conversion factor
simulation:
    MASS2: ['birch_tga_1step_2_devc.csv','MASS',1.0]
    MASS20: ['birch_tga_1step_20_devc.csv','MASS',1.0]
experiment:
    MASS2: ['birch_tga_2_exp.csv','Mass',1.0]
    MASS20: ['birch_tga_20_exp.csv','Mass',1.0]
obejctive:
    type: "RMSE"
    weights: {'MLR': 1.0, 'HRR': 0.0}
plotting:
    MLR: {ylabel: "MLR (g/m$^2$s)", xlabel: "Time (s)"}
    HRR: {ylabel: "MLR (g/m$^2$s)", xlabel: "Time (s)"}
optimizer:
         base_estimator:        'GP'
         acq_func:              'EI'
         acq_optimizer:         'auto'
         n_initial_points:      36 
         acq_optimizer_kwargs:  {n_points: 10000, n_restarts_optimizer": 5,n_jobs: 1}
         acq_func_kwargs:       {xi: 0.05, kappa: 0.96}
templates: ["birch_cone.fds"]
#end_config
