#start_config
num_jobs: 10 # number of parallel jobs
max_iter: 10 # maximum number of iterations
num_points: 10  # How many points explored per iteration
num_initial: 120 # Number of points in initial design (here 10*ndim)
initial_design: lhs
# full path to fds executable
fds_command: /home/tstopi/Firemodels/fds/Build/mpi_intel_linux_64/fds_mpi_intel_linux_64 
variables: # VAR_NAME: [LOWER,UPPER]
    HOR: [300,500]
    K_S_20: [0.1 ,0.4]
    K_S_300: [0.2,0.5]
    K_S_600: [0.2,0.6]
    C_S_20: [1,3]
    C_S_300: [1 ,3]
    C_S_600: [1 ,3]
    RHO_C: [100,400]
    K_C: [0.1,0.6]
    C_C: [1,3]
simulation:
    MLR35: {fname: 'birch_cone_35_hrr.csv',dep_col_name: 'MLR',conversion_factor: 1000}
    MLR50: {fname: 'birch_cone_50_hrr.csv',dep_col_name: 'MLR',conversion_factor: 1000}
    MLR75: {fname: 'birch_cone_75_hrr.csv',dep_col_name: 'MLR',conversion_factor: 1000}
    HRR35: {fname: 'birch_cone_35_hrr.csv',dep_col_name: 'HRR',conversion_factor: 100}
    HRR50: {fname: 'birch_cone_50_hrr.csv',dep_col_name: 'HRR',conversion_factor: 100}
    HRR75: {fname: 'birch_cone_75_hrr.csv',dep_col_name: 'HRR',conversion_factor: 100}
experiment:
    MLR35: {fname: 'Experimental_Data/Birch_35kW.csv',dep_col_name: 'MLR',header: 1}
    MLR50: {fname: 'Experimental_Data/Birch_50kW.csv',dep_col_name: 'MLR',header: 1}
    MLR75: {fname: 'Experimental_Data/Birch_75kW.csv',dep_col_name: 'MLR',header: 1}
    HRR35: {fname: 'Experimental_Data/Birch_35kW.csv',dep_col_name: 'HRR',header: 1}
    HRR50: {fname: 'Experimental_Data/Birch_50kW.csv',dep_col_name: 'HRR',header: 1}
    HRR75: {fname: 'Experimental_Data/Birch_75kW.csv',dep_col_name: 'HRR',header: 1}
obejctive:
    type: "mse"
plots:
    expMLR: 
        variables: ["MLR35","MLR50","MLR75"]
        labels: ["35 kW/m2","50 kW/m2","75 kW/m2"]
        type: "experimental"
        ylabel: "MLR (g/s)"
        xlabel: "Time (s)"
    expHRR: 
        variables: ["HRR35","HRR50","HRR75"]
        labels: ["35 kW/m2","50 kW/m2","75 kW/m2"]
        type: "experimental"
        ylabel: "MLR (g/s)"
        xlabel: "Temp (C)"
    cmpMLR: 
        variables: ["MLR35","MLR50","MLR75"]
        labels: ["35 kW/m2","50 kW/m2","75 kW/m2"]
        type: "comparison"
        ylabel: "MLR (g/s)"
        xlabel: "Time (s)"
    cmpHRR: 
        variables: ["HRR35","HRR50","HRR75"]
        labels: ["35 kW/m2","50 kW/m2","75 kW/m2"]
        type: "comparison"
        ylabel: "MLR (g/s)"
        xlabel: "Temp (C)"
templates: ["birch_cone_35.fds","birch_cone_50.fds","birch_cone_75.fds"]
optimizer_name: "skopt"
optimizer:
         base_estimator:        'gp'
         acq_func:              'EI'
         acq_optimizer:         'auto'
         n_initial_points:      1
         acq_optimizer_kwargs:  {n_points: 100000, n_restarts_optimizer": 10,n_jobs: 1}
         acq_func_kwargs:       {xi: 0.01, kappa: 1.96}
